name_or_path: gpt2-large
tokenizer_name_or_path: null
num_heads: 3  # Number of preference dimensions
archive: null
block_name: GPT2Block

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16